# Import necessary enterprise libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# ==========================================
# STEP 1: LOAD THE TRAINING DATA
# ==========================================
# We ONLY use the training data to figure out which features are important.
try:
    X_train = pd.read_csv("X_train.csv")
    y_train = pd.read_csv("y_train.csv")
    X_test = pd.read_csv("X_test.csv") # We load this just so we can filter it later
    print("Successfully loaded the split datasets from Task 2.")
except FileNotFoundError:
    print("Error: Could not find 'X_train.csv'. Make sure you ran Task 2 successfully.")
    exit()

# Format the target variable correctly for the machine learning model
y_train = y_train.values.ravel()

# ==========================================
# STEP 2: CALCULATE FEATURE IMPORTANCE
# ==========================================
print("\nAnalyzing feature importance using a Random Forest...")

# Train a quick model specifically to score the features
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Extract the scores generated by the model
importances = rf_model.feature_importances_

# Create a clean table to view the scores
feature_importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': importances
})

# Sort features so the highest scores are at the top
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

print("\n--- TOP 10 MOST IMPORTANT FEATURES ---")
print(feature_importance_df.head(10).to_string(index=False))

# ==========================================
# STEP 3: FILTER OUT THE WEAK FEATURES
# ==========================================
# We set a threshold. Any feature scoring below 0.02 is dropped.
threshold = 0.02
top_features = feature_importance_df[feature_importance_df['Importance'] > threshold]['Feature'].tolist()

print(f"\nFiltering down to the top {len(top_features)} most predictive features...")

# Create new datasets keeping ONLY the top features
X_train_selected = X_train[top_features]
X_test_selected = X_test[top_features] # We apply the exact same filter to the test data

# ==========================================
# STEP 4: VERIFY AND SAVE
# ==========================================
print(f"\nFinal Training Features Shape: {X_train_selected.shape}")
print(f"Final Testing Features Shape: {X_test_selected.shape}")

# Save these optimized datasets so we can use them to train the final model
X_train_selected.to_csv("X_train_selected.csv", index=False)
X_test_selected.to_csv("X_test_selected.csv", index=False)

print("\nSuccess! Saved selected features to 'X_train_selected.csv' and 'X_test_selected.csv'")